app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user_security:
  resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_registration:
  resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
  prefix: "/account/register"

fos_user_resetting:
  resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"