dashboard:
  route: 'app.admin.index'
  icon: 'fa-tachometer'
  title: 'Dashboard'
  submenu: null

catalog:
  title: Catalog
  icon: 'fa-tags'
  route: null
  submenu:
    category:
      route: 'app.admin.category.list'
      title: 'Categories'
      submenu: null
    product:
      route: 'app.admin.product.list'
      title: 'Products'
      submenu: null